In [1]:
from keras.models import load_model

Using TensorFlow backend.
C:\Users\KIIT\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\KIIT\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\KIIT\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\KIIT\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519

In [2]:
model= load_model('facedetect.h5')

In [3]:
import cv2
import numpy as np
import os
import IPython.display as ipd
import PIL
from keras.preprocessing import image

In [4]:
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


In [5]:
def face_detector(img, size=0.5):

    # Convert image to grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    if faces is ():
        return img, []

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (224, 224))          #desired format for vgg16
    return img, roi

In [6]:

# Open Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()

    image, face = face_detector(frame)
    face=np.array(face)
    face= np.expand_dims(face, axis=0)
    if(face.shape==(1,0)):
        cv2.putText(image, "I don't know", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.imshow('Face Recognition', image )
    
    else:
        # Pass face to prediction model
        # "results" comprises of a tuple containing the label and the confidence value
        results = model.predict(face)
        print(results)
        if(results[0][0] == 1.0):
            cv2.putText(image, "Tanya", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition', image )

        elif(results[0][0] != 1.0):
            cv2.putText(image, "Tushar", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition', image )
            
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()

[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[1.0797334e-04 9.9989200e-01]]
[[0. 1.]]
[[4.995321e-22 1.000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[2.3401151e-31 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[5.6620646e-28 1.0000000e+00]]
[[1.6064708e-10 1.0000000e+00]]
[[4.2188513e-13 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[6.2979038e-24 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[1.7898906e-09 1.0000000e+00]]
[[0.00952106 0.99047893]]
[[1.9125025e-19 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[2.245922e-23 1.000000e+00]]
[[3.9242372e-23 1.0000000e+00]]
[[1. 0.]]
[[7.6107238e-04 9.9923897e-01]]
[[1.000000e+00 1.389241e-09]]
[[1.6958585e-18 1.0000000e+00]]
[[1.3293033e-33 1.0000000e+00]]
[[8.185284e-28 1.000000e+00]]
[[1.1615686e-25 1.0000000e+00]]
[[5.515717e-26 1.000000e+00]]
[[1.000000e+00 9.691684e-20]]
[[1.0224508e-28 1.0000000e+00]]
[[1.5665395e-20 1.0000000e